export const LEVEL_DATA_REQUEST = 'NEXT_LEVEL_REQUEST';
export const LEVEL_DATA_RECEIVED = 'LEVEL_DATA_RECEIVED';
export const COPY_REQUEST = 'COPY_REQUEST';
export const MOVE_REQUEST = 'MOVE_REQUEST';
export const PASTE_REQUEST = 'PASTE_REQUEST';
export const PASTE_REQUEST_DONE = 'PASTE_REQUEST_DONE';
export const SAVE_DEST_PATH = 'SAVE_DEST_PATH';
